---
sudo: false
before_install:
- eval "$(ssh-agent -s)"
- openssl aes-256-cbc -K $encrypted_7be621dcca6e_key -iv $encrypted_7be621dcca6e_iv
  -in travis.enc -out travis -d
- chmod 600 travis
- ssh-add travis
branches:
  only:
    - master
script: make deploy
