baseURL = "http://mysqlusers.be/"
languageCode = "en-us"
title = "MySQL & Friends Belgium"
theme = "cocoa-eh"

[params]
dateform = "Jan 2, 2006"
dateformfull = "Mon Jan 2 2006 15:04:05 MST"
logofile = "img/logo.png"
